### ISSUE TITLE
_tkinter.TclError: couldn't open "hypercube_viewer\resources\icons\hypercube_viewer_icon.png": no such file or directory

### ISSUE THREAD

**Issue by jcroad90** [BSmith156/Hypercube-Viewer#1]
Traceback (most recent call last):
  File "hypercube_viewer.py", line 3, in <module>
    app.run()
  File "/home/jack/Hypercube-Viewer/hypercube_viewer/app.py", line 10, in run
    icon = tk.PhotoImage(file = "hypercube_viewer\\resources\\icons\\hypercube_viewer_icon.png")
  File "/usr/lib/python3.6/tkinter/__init__.py", line 3545, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 3501, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "hypercube_viewer\resources\icons\hypercube_viewer_icon.png": no such file or directory

**Comment by BSmith156** [comment]
Hmm weird, what OS are you using? I’v only been able to test on Windows.

**Comment by BSmith156** [comment]
It’s only the window icon, nothing important, so I’v added a try statement around it. It’s not a permanent fix but at least it’ll run now.
